print(".Rprofile")
Sys.getenv("R_LIBS_USER")
Sys.getenv("HOME")
Sys.getenv("RENV_PATHS_ROOT")
Sys.getenv("RENV_PATHS_LIBRARY")
.libPaths()

options(repos = c(CRAN = "https://cloud.r-project.org"))
Sys.setenv(RENV_CONFIG_RSPM_ENABLED = FALSE)
#source("renv/activate.R")
